version: "3.4"

services:
  beammp-server:
    image: beezu/beammp-server
    volumes:
      # Just move all the client mods you want to add into this folder
      - ./client-mods:/beammp/Resources/Client
      # All server mods belong here
      - ./server-mods:/beammp/Resources/Server
      # Add your pre-existing config file here
      - ./ServerConfig.toml:/beammp/ServerConfig.toml
    ports:
      - "${PORT}:${PORT}/tcp"
      - "${PORT}:${PORT}/udp"
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
